### ISSUE TITLE
How deploy spring-petclinic-cloud to k8s without wavefront?

### ISSUE THREAD

**Issue by patsevanton** [spring-petclinic/spring-petclinic-cloud#39]
Hello!
I try run spring-petclinic-cloud in kubernetes locally.
I get error.
How deploy spring-petclinic-cloud to k8s without wavefront?

```
api-gateway-87b794774-kn2rc api-gateway 2021-10-28 10:18:45.674 ERROR [api-gateway,,,] 1 --- [tClientSender-0] c.w.s.c.c.service.ReportingService       : Unable to obtain status code from the Wavefront service at http://wavefront-proxy.spring-petclinic.svc.cluster.local:2878/report?f=trace
api-gateway-87b794774-kn2rc api-gateway 
api-gateway-87b794774-kn2rc api-gateway java.net.UnknownHostException: wavefront-proxy.spring-petclinic.svc.cluster.local
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.net.Socket.connect(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at com.wavefront.sdk.common.clients.service.ReportingService.safeGetResponseCodeAndClose(ReportingService.java:77)
api-gateway-87b794774-kn2rc api-gateway         at com.wavefront.sdk.common.clients.service.ReportingService.send(ReportingService.java:68)
api-gateway-87b794774-kn2rc api-gateway         at com.wavefront.sdk.common.clients.WavefrontClient.internalFlush(WavefrontClient.java:515)
api-gateway-87b794774-kn2rc api-gateway         at com.wavefront.sdk.common.clients.WavefrontClient.flushNoCheck(WavefrontClient.java:472)
api-gateway-87b794774-kn2rc api-gateway         at com.wavefront.sdk.common.clients.WavefrontClient.flush(WavefrontClient.java:460)
api-gateway-87b794774-kn2rc api-gateway         at com.wavefront.sdk.common.clients.WavefrontClient.run(WavefrontClient.java:448)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api-gateway-87b794774-kn2rc api-gateway         at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by snicoll** [comment]
I think we should keep this conversation here. The configuration to disable the endpoint should be read soon enough (that is not via configuration server). How is this configuration file loaded ?

**Comment by patsevanton** [comment]
@snicoll I am sorry. I am DevOps engineer. Where i can find configuration file ?

**Comment by snicoll** [comment]
@patsevanton sorry I've noticed that you did answered my question already. I am not sure `bootstrap.yml` is the best place for this. See also the [issue I've created](https://github.com/spring-petclinic/spring-petclinic-cloud/issues/40).

**Comment by patsevanton** [comment]
any news?

**Comment by arey** [comment]
Yes see https://github.com/spring-petclinic/spring-petclinic-cloud/pull/43
